// Code generated by 'go generate'; DO NOT EDIT.

package registry

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
	"golang.org/x/sys/windows/registry"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modadvapi32 = windows.NewLazySystemDLL("advapi32.dll")

	procRegDeleteKeyValueW = modadvapi32.NewProc("RegDeleteKeyValueW")
	procRegGetValueW       = modadvapi32.NewProc("RegGetValueW")
	procRegSetKeyValueW    = modadvapi32.NewProc("RegSetKeyValueW")
)

func regDeleteKeyValue(key registry.Key, subKey *uint16, valueName *uint16) (ret error) {
	r0, _, _ := syscall.SyscallN(procRegDeleteKeyValueW.Addr(), uintptr(key), uintptr(unsafe.Pointer(subKey)), uintptr(unsafe.Pointer(valueName)))
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func regGetValue(key registry.Key, subKey *uint16, valueName *uint16, flags uint32, valueType *uint32, pData unsafe.Pointer, cbData *uint32) (ret error) {
	r0, _, _ := syscall.SyscallN(procRegGetValueW.Addr(), uintptr(key), uintptr(unsafe.Pointer(subKey)), uintptr(unsafe.Pointer(valueName)), uintptr(flags), uintptr(unsafe.Pointer(valueType)), uintptr(pData), uintptr(unsafe.Pointer(cbData)))
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}

func regSetKeyValue(key registry.Key, subKey *uint16, valueName *uint16, valueType uint32, pData unsafe.Pointer, cbData uint32) (ret error) {
	r0, _, _ := syscall.SyscallN(procRegSetKeyValueW.Addr(), uintptr(key), uintptr(unsafe.Pointer(subKey)), uintptr(unsafe.Pointer(valueName)), uintptr(valueType), uintptr(pData), uintptr(cbData))
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}
